spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.105.26:3306/user_center
    username: usercenter
    password: 1qazxsw2#E
  session:
    timeout: 86400
